version: "3"

services:
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  metarank_standalone:
    container_name: metarank_standalone
    image: metarank/metarank:latest
    depends_on:
      - redis
    command: "standalone --config /data/config.yml --data /data/events.jsonl.gz"
    volumes:
      - ./metarank:/data
    ports:
      - "8080:8080"
      - "6123:6123"