state:
  type: redis
  host: redis
  port: 6379

models:
  xgboost:
    type: lambdamart
    backend:
      type: lightgbm
      iterations: 50
      ndcgCutoff: 50
      seed: 0
    weights:
      click: 1
    features:
      - genre
      - liked_genre
      - liked_actors
features:
  - name: genre
    type: string
    scope: item
    source: metadata.genres
    values:
      - drama
      - comedy
      - thriller
      - action
      - adventure
      - romance
      - crime
      - science fiction
      - fantasy
      - family
      - horror
      - mystery
      - animation
      - history
      - music
  - name: liked_genre
    type: interacted_with
    interaction: click
    field: metadata.genres
    scope: session
    count: 100
    duration: 24h
  - name: liked_actors
    type: interacted_with
    interaction: click
    field: metadata.actors
    scope: session
    count: 100
    duration: 24h
api:
  port: 8080
  host: "0.0.0.0"